name: Deploy thrifting-app-service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build . -t ikhsanhilmi/thrifting-app-service

      - name: Push Docker Image to Docker Hub
        run: docker push ikhsanhilmi/thrifting-app-service

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull ikhsanhilmi/thrifting-app-service

      - name: Delete old docker container
        run: |
          docker stop thrifting-app-service-app || true
          docker rm thrifting-app-service-app || true

      - name: Run New Docker Container
        run: |
          docker run -d \
          -p 9002:9002 \
          -e DB_HOST="${{ secrets.DB_HOST }}" \
          -e DB_PORT="${{ secrets.DB_PORT }}" \
          -e DB_NAME="${{ secrets.DB_NAME }}" \
          -e DB_USER="${{ secrets.DB_USER }}" \
          -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          -e APP_NAME="${{ secrets.APP_NAME }}" \
          -e PORT="${{ secrets.PORT }}" \
          -e APP_SECRET="${{ secrets.APP_SECRET }}" \
          --name thrifting-app-service \
          ikhsanhilmi/thrifting-app-service
